### ISSUE TITLE
001.dnn.ipynb エラー

### ISSUE THREAD

**Issue by TakaakiSaito613** [sugiyama34/AIciaSolidProject#53]
001.dnn.ipynbのコードを回してみたのですが、以下のpdfファイルに示したようなエラーが表示されました。色々と調べてみたのですが、解決しなかったのでissueとして送らせていただきました。

[001.dnn - Jupyter Notebook.pdf](https://github.com/sugiyama34/AIciaSolidProject/files/5901881/001.dnn.-.Jupyter.Notebook.pdf)

**Comment by sugiyama34** [comment]
@TakaakiSaito613 ありがとうございます！
たしかに動きませんね！／(^o^)＼

その notebook があるフォルダに、 `DNN` という名称のフォルダを作ってみてください。
そしたら動きませんか？

**Comment by TakaakiSaito613** [comment]
ご返信ありがとうございます。

modelsというフォルダを作り、その中にDNNというフォルダを作ったら動きました！
とても楽しいです☆本当にありがとうございました！
引き続き他の動画も拝見させていただきます！

**Comment by sugiyama34** [comment]
よかったです！

あとでフォルダがあるバージョンを push しておきます🙇‍♂️

**Comment by sugiyama34** [comment]
close されない、なぜじゃー
#58 で対処
